name: "DEV DEPLOY"

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  terraform:
    uses: ./.github/workflows/terraform.yml
    with:
      environment: prod
      aws-assume-role-arn: "arn:aws:iam::058264483404:role/github-actions-kadu3611"
      aws-region: "us-east-2"
      aws-statefile-s3-bucket: "kadu-terraform-statefile"
      aws-lock-dynamodb-table: "Tabela-Terraform"