name: "DEV DEPLOY"

on: 
  push:
    branches:
      - develop

permissions:
      id-token: write
      contents: read

jobs:
  terraform:
    uses:  ./.github/workflows/terraform.yml
    with: 
      enviremont: dev
      aws-assume-role-arn: "arn:aws:iam::058264483404:role/github-actions-kadu3611"
      aws-region: "sa-east-1"
      aws-statefile-s3-bucket: "kadu-terraform-statefile"
      aws-lock-dynamodb-table: "Tabela-Terraform"